### ISSUE TITLE
Any chance to support image v0.25?

### ISSUE THREAD

**Issue by CrendKing** [qarmin/img_hash#16]
image is updated to [v0.25](https://github.com/image-rs/image/blob/main/CHANGES.md#version-0250). Currently this repo can only use [v0.24.*](https://github.com/qarmin/img_hash/blob/699a8b9500386cfc474d10de8d444e6a7814685d/Cargo.toml#L21). Any chance we can bump that dependency?

**Comment by qarmin** [comment]
0% chance

**Comment by qarmin** [comment]
Version 2.0.0 with image-rs 0.25.0 is already released on crates.io
